# Generated by Django 5.1.1 on 2024-10-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltaje', models.FloatField()),
                ('rs', models.FloatField()),
                ('calidad_aire', models.CharField(max_length=100)),
            ],
        ),
    ]
